// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPb80PSqZZgMbQYS1H0nqTZiVgtnDwT5I',
    appId: '1:159391595796:web:590505e6cae318661d5601',
    messagingSenderId: '159391595796',
    projectId: 'workspace-7d49d',
    authDomain: 'workspace-7d49d.firebaseapp.com',
    storageBucket: 'workspace-7d49d.firebasestorage.app',
    measurementId: 'G-LN31SVD8LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClIVr3DWVP-HR55kgBXHnNJYFAA8dH9hE',
    appId: '1:159391595796:android:3da8c80927a249781d5601',
    messagingSenderId: '159391595796',
    projectId: 'workspace-7d49d',
    storageBucket: 'workspace-7d49d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2YIMBXFW9ip4_yPCUgh-xOntzjpOTU7Y',
    appId: '1:159391595796:ios:05225ca24592c23a1d5601',
    messagingSenderId: '159391595796',
    projectId: 'workspace-7d49d',
    storageBucket: 'workspace-7d49d.firebasestorage.app',
    iosBundleId: 'com.example.workSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2YIMBXFW9ip4_yPCUgh-xOntzjpOTU7Y',
    appId: '1:159391595796:ios:05225ca24592c23a1d5601',
    messagingSenderId: '159391595796',
    projectId: 'workspace-7d49d',
    storageBucket: 'workspace-7d49d.firebasestorage.app',
    iosBundleId: 'com.example.workSpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPb80PSqZZgMbQYS1H0nqTZiVgtnDwT5I',
    appId: '1:159391595796:web:a776525ade81c5821d5601',
    messagingSenderId: '159391595796',
    projectId: 'workspace-7d49d',
    authDomain: 'workspace-7d49d.firebaseapp.com',
    storageBucket: 'workspace-7d49d.firebasestorage.app',
    measurementId: 'G-DE5MF4YGVY',
  );
}
